Metrics/LineLength:
  Max: 100

Naming/MethodParameterName:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/EmptyMethod:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/Documentation:
  Enabled: False

Style/DocumentationMethod:
  Enabled: False

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/CaseIndentation:
  IndentOneStep: true

Layout/LeadingCommentSpace:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
